# Generated by Django 6.0.2 on 2026-02-24 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_persons', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente'), ('eliminar', 'Eliminar')])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.service')),
            ],
        ),
    ]
