# Generated by Django 6.0.2 on 2026-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, help_text='Ruta de Vercel (ej: /images/servicio1.jpg)', max_length=500, null=True),
        ),
    ]
