# Generated by Django 6.0.2 on 2026-02-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=700)),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='services/')),
            ],
        ),
    ]
